// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference.proto

package inferencev1

import (
	datamodelv1 "github.com/NVIDIA/OpenShell/sdk/go/proto/datamodelv1"
	_ "github.com/NVIDIA/OpenShell/sdk/go/proto/optionsv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Persisted inference route configuration.
//
// Only `provider_name` and `model_id` are stored; endpoint, protocols,
// credentials, and auth style are resolved from the provider at bundle time.
type InferenceRouteConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider record name backing this route.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Model identifier to force on generation calls.
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Per-route request timeout in seconds. 0 means use default (60s).
	TimeoutSecs   uint64 `protobuf:"varint,3,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRouteConfig) Reset() {
	*x = InferenceRouteConfig{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRouteConfig) ProtoMessage() {}

func (x *InferenceRouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRouteConfig.ProtoReflect.Descriptor instead.
func (*InferenceRouteConfig) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceRouteConfig) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *InferenceRouteConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferenceRouteConfig) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

// Storage envelope for a workspace-scoped inference route.
type InferenceRoute struct {
	state    protoimpl.MessageState  `protogen:"open.v1"`
	Metadata *datamodelv1.ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Config   *InferenceRouteConfig   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Monotonic version incremented on every update.
	Version       uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRoute) Reset() {
	*x = InferenceRoute{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRoute) ProtoMessage() {}

func (x *InferenceRoute) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRoute.ProtoReflect.Descriptor instead.
func (*InferenceRoute) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceRoute) GetMetadata() *datamodelv1.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InferenceRoute) GetConfig() *InferenceRouteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InferenceRoute) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SetInferenceRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider record name to use for credentials + endpoint mapping.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Model identifier to force on generation calls.
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// Route name to target. Empty string defaults to "inference.local" (user-facing).
	// Use "sandbox-system" for the sandbox system-level inference route.
	RouteName string `protobuf:"bytes,3,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// Verify the resolved upstream endpoint synchronously before persistence.
	Verify bool `protobuf:"varint,4,opt,name=verify,proto3" json:"verify,omitempty"`
	// Skip synchronous endpoint validation before persistence.
	NoVerify bool `protobuf:"varint,5,opt,name=no_verify,json=noVerify,proto3" json:"no_verify,omitempty"`
	// Per-route request timeout in seconds. 0 means use default (60s).
	TimeoutSecs uint64 `protobuf:"varint,6,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	// Target workspace. Empty string defaults to "default".
	Workspace     string `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInferenceRouteRequest) Reset() {
	*x = SetInferenceRouteRequest{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInferenceRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInferenceRouteRequest) ProtoMessage() {}

func (x *SetInferenceRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInferenceRouteRequest.ProtoReflect.Descriptor instead.
func (*SetInferenceRouteRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *SetInferenceRouteRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetInferenceRouteRequest) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *SetInferenceRouteRequest) GetNoVerify() bool {
	if x != nil {
		return x.NoVerify
	}
	return false
}

func (x *SetInferenceRouteRequest) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *SetInferenceRouteRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type ValidatedEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatedEndpoint) Reset() {
	*x = ValidatedEndpoint{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedEndpoint) ProtoMessage() {}

func (x *ValidatedEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedEndpoint.ProtoReflect.Descriptor instead.
func (*ValidatedEndpoint) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatedEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ValidatedEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type SetInferenceRouteResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProviderName string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId      string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version      uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Route name that was configured.
	RouteName string `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// Whether endpoint verification ran as part of this request.
	ValidationPerformed bool `protobuf:"varint,5,opt,name=validation_performed,json=validationPerformed,proto3" json:"validation_performed,omitempty"`
	// The concrete endpoints that were probed during validation, when available.
	ValidatedEndpoints []*ValidatedEndpoint `protobuf:"bytes,6,rep,name=validated_endpoints,json=validatedEndpoints,proto3" json:"validated_endpoints,omitempty"`
	// Per-route request timeout in seconds that was persisted.
	TimeoutSecs uint64 `protobuf:"varint,7,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	// Workspace the route was configured in.
	Workspace     string `protobuf:"bytes,8,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInferenceRouteResponse) Reset() {
	*x = SetInferenceRouteResponse{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInferenceRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInferenceRouteResponse) ProtoMessage() {}

func (x *SetInferenceRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInferenceRouteResponse.ProtoReflect.Descriptor instead.
func (*SetInferenceRouteResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *SetInferenceRouteResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SetInferenceRouteResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetInferenceRouteResponse) GetValidationPerformed() bool {
	if x != nil {
		return x.ValidationPerformed
	}
	return false
}

func (x *SetInferenceRouteResponse) GetValidatedEndpoints() []*ValidatedEndpoint {
	if x != nil {
		return x.ValidatedEndpoints
	}
	return nil
}

func (x *SetInferenceRouteResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *SetInferenceRouteResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetInferenceRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Route name to query. Empty string defaults to "inference.local" (user-facing).
	// Use "sandbox-system" for the sandbox system-level inference route.
	RouteName string `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// Target workspace. Empty string defaults to "default".
	Workspace     string `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceRouteRequest) Reset() {
	*x = GetInferenceRouteRequest{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceRouteRequest) ProtoMessage() {}

func (x *GetInferenceRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceRouteRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceRouteRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *GetInferenceRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetInferenceRouteRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetInferenceRouteResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProviderName string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId      string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version      uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Route name that was queried.
	RouteName string `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// Per-route request timeout in seconds. 0 means default (60s).
	TimeoutSecs uint64 `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	// Workspace the route belongs to.
	Workspace     string `protobuf:"bytes,6,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceRouteResponse) Reset() {
	*x = GetInferenceRouteResponse{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceRouteResponse) ProtoMessage() {}

func (x *GetInferenceRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceRouteResponse.ProtoReflect.Descriptor instead.
func (*GetInferenceRouteResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *GetInferenceRouteResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetInferenceRouteResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetInferenceRouteResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *GetInferenceRouteResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteInferenceRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Route name to delete. Empty string defaults to "inference.local" (user-facing).
	// Use "sandbox-system" for the sandbox system-level inference route.
	RouteName string `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	// Target workspace. Empty string defaults to "default".
	Workspace     string `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInferenceRouteRequest) Reset() {
	*x = DeleteInferenceRouteRequest{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInferenceRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInferenceRouteRequest) ProtoMessage() {}

func (x *DeleteInferenceRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInferenceRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteInferenceRouteRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInferenceRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *DeleteInferenceRouteRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteInferenceRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a route was actually deleted.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInferenceRouteResponse) Reset() {
	*x = DeleteInferenceRouteResponse{}
	mi := &file_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInferenceRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInferenceRouteResponse) ProtoMessage() {}

func (x *DeleteInferenceRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInferenceRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteInferenceRouteResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteInferenceRouteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetInferenceBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceBundleRequest) Reset() {
	*x = GetInferenceBundleRequest{}
	mi := &file_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceBundleRequest) ProtoMessage() {}

func (x *GetInferenceBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceBundleRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceBundleRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{9}
}

// A single resolved route ready for sandbox-local execution.
type ResolvedRoute struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl      string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Protocols    []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	ApiKey       string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ModelId      string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProviderType string                 `protobuf:"bytes,6,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	// Per-route request timeout in seconds. 0 means use default (60s).
	TimeoutSecs uint64 `protobuf:"varint,7,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	// When true, the model identifier is embedded in the URL path (e.g. Vertex AI).
	ModelInPath bool `protobuf:"varint,8,opt,name=model_in_path,json=modelInPath,proto3" json:"model_in_path,omitempty"`
	// Optional override for the request path. When set, replaces the protocol-derived path.
	// An empty string means POST directly to base_url/model_id with no additional path.
	RequestPathOverride *string `protobuf:"bytes,9,opt,name=request_path_override,json=requestPathOverride,proto3,oneof" json:"request_path_override,omitempty"`
	// Absolute credential expiry. The sandbox router enforces this locally so a
	// stale bundle cannot keep using an expired grant while the gateway is down.
	CredentialExpiresAtMs int64 `protobuf:"varint,10,opt,name=credential_expires_at_ms,json=credentialExpiresAtMs,proto3" json:"credential_expires_at_ms,omitempty"`
	// Gateway-resolved headers that are not agent-controlled. Values may contain
	// account-routing material and must be treated with the same secrecy as api_key.
	DefaultHeaders map[string]string `protobuf:"bytes,11,rep,name=default_headers,json=defaultHeaders,proto3" json:"default_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedRoute) Reset() {
	*x = ResolvedRoute{}
	mi := &file_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedRoute) ProtoMessage() {}

func (x *ResolvedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedRoute.ProtoReflect.Descriptor instead.
func (*ResolvedRoute) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{10}
}

func (x *ResolvedRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedRoute) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ResolvedRoute) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *ResolvedRoute) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ResolvedRoute) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ResolvedRoute) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ResolvedRoute) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *ResolvedRoute) GetModelInPath() bool {
	if x != nil {
		return x.ModelInPath
	}
	return false
}

func (x *ResolvedRoute) GetRequestPathOverride() string {
	if x != nil && x.RequestPathOverride != nil {
		return *x.RequestPathOverride
	}
	return ""
}

func (x *ResolvedRoute) GetCredentialExpiresAtMs() int64 {
	if x != nil {
		return x.CredentialExpiresAtMs
	}
	return 0
}

func (x *ResolvedRoute) GetDefaultHeaders() map[string]string {
	if x != nil {
		return x.DefaultHeaders
	}
	return nil
}

type GetInferenceBundleResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Routes []*ResolvedRoute       `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Opaque revision tag for cache freshness checks.
	Revision string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// Timestamp (epoch ms) when this bundle was generated.
	GeneratedAtMs int64 `protobuf:"varint,3,opt,name=generated_at_ms,json=generatedAtMs,proto3" json:"generated_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceBundleResponse) Reset() {
	*x = GetInferenceBundleResponse{}
	mi := &file_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceBundleResponse) ProtoMessage() {}

func (x *GetInferenceBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceBundleResponse.ProtoReflect.Descriptor instead.
func (*GetInferenceBundleResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{11}
}

func (x *GetInferenceBundleResponse) GetRoutes() []*ResolvedRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetInferenceBundleResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetInferenceBundleResponse) GetGeneratedAtMs() int64 {
	if x != nil {
		return x.GeneratedAtMs
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x16openshell.inference.v1\x1a\x0fdatamodel.proto\x1a\roptions.proto\"y\n" +
	"\x14InferenceRouteConfig\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12!\n" +
	"\ftimeout_secs\x18\x03 \x01(\x04R\vtimeoutSecs\"\xb0\x01\n" +
	"\x0eInferenceRoute\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".openshell.datamodel.v1.ObjectMetaR\bmetadata\x12D\n" +
	"\x06config\x18\x02 \x01(\v2,.openshell.inference.v1.InferenceRouteConfigR\x06config\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\xef\x01\n" +
	"\x18SetInferenceRouteRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x03 \x01(\tR\trouteName\x12\x16\n" +
	"\x06verify\x18\x04 \x01(\bR\x06verify\x12\x1b\n" +
	"\tno_verify\x18\x05 \x01(\bR\bnoVerify\x12!\n" +
	"\ftimeout_secs\x18\x06 \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\"A\n" +
	"\x11ValidatedEndpoint\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\"\xe4\x02\n" +
	"\x19SetInferenceRouteResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x121\n" +
	"\x14validation_performed\x18\x05 \x01(\bR\x13validationPerformed\x12Z\n" +
	"\x13validated_endpoints\x18\x06 \x03(\v2).openshell.inference.v1.ValidatedEndpointR\x12validatedEndpoints\x12!\n" +
	"\ftimeout_secs\x18\a \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\b \x01(\tR\tworkspace\"W\n" +
	"\x18GetInferenceRouteRequest\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\tR\trouteName\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"\xd5\x01\n" +
	"\x19GetInferenceRouteResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x04R\vtimeoutSecs\x12\x1c\n" +
	"\tworkspace\x18\x06 \x01(\tR\tworkspace\"Z\n" +
	"\x1bDeleteInferenceRouteRequest\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\tR\trouteName\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"8\n" +
	"\x1cDeleteInferenceRouteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x1b\n" +
	"\x19GetInferenceBundleRequest\"\xbb\x04\n" +
	"\rResolvedRoute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x1d\n" +
	"\aapi_key\x18\x04 \x01(\tB\x04\x88\xb5\x18\x01R\x06apiKey\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12#\n" +
	"\rprovider_type\x18\x06 \x01(\tR\fproviderType\x12!\n" +
	"\ftimeout_secs\x18\a \x01(\x04R\vtimeoutSecs\x12\"\n" +
	"\rmodel_in_path\x18\b \x01(\bR\vmodelInPath\x127\n" +
	"\x15request_path_override\x18\t \x01(\tH\x00R\x13requestPathOverride\x88\x01\x01\x127\n" +
	"\x18credential_expires_at_ms\x18\n" +
	" \x01(\x03R\x15credentialExpiresAtMs\x12h\n" +
	"\x0fdefault_headers\x18\v \x03(\v29.openshell.inference.v1.ResolvedRoute.DefaultHeadersEntryB\x04\x88\xb5\x18\x01R\x0edefaultHeaders\x1aA\n" +
	"\x13DefaultHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x18\n" +
	"\x16_request_path_override\"\x9f\x01\n" +
	"\x1aGetInferenceBundleResponse\x12=\n" +
	"\x06routes\x18\x01 \x03(\v2%.openshell.inference.v1.ResolvedRouteR\x06routes\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12&\n" +
	"\x0fgenerated_at_ms\x18\x03 \x01(\x03R\rgeneratedAtMs2\x82\x05\n" +
	"\tInference\x12\x8a\x01\n" +
	"\x12GetInferenceBundle\x121.openshell.inference.v1.GetInferenceBundleRequest\x1a2.openshell.inference.v1.GetInferenceBundleResponse\"\r\x82\xb5\x18\t\n" +
	"\asandbox\x12\x9e\x01\n" +
	"\x11SetInferenceRoute\x120.openshell.inference.v1.SetInferenceRouteRequest\x1a1.openshell.inference.v1.SetInferenceRouteResponse\"$\x82\xb5\x18 \n" +
	"\x06bearer\x12\x05admin\"\x0finference:write\x12\x9c\x01\n" +
	"\x11GetInferenceRoute\x120.openshell.inference.v1.GetInferenceRouteRequest\x1a1.openshell.inference.v1.GetInferenceRouteResponse\"\"\x82\xb5\x18\x1e\n" +
	"\x06bearer\x12\x04user\"\x0einference:read\x12\xa7\x01\n" +
	"\x14DeleteInferenceRoute\x123.openshell.inference.v1.DeleteInferenceRouteRequest\x1a4.openshell.inference.v1.DeleteInferenceRouteResponse\"$\x82\xb5\x18 \n" +
	"\x06bearer\x12\x05admin\"\x0finference:writeb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_inference_proto_goTypes = []any{
	(*InferenceRouteConfig)(nil),         // 0: openshell.inference.v1.InferenceRouteConfig
	(*InferenceRoute)(nil),               // 1: openshell.inference.v1.InferenceRoute
	(*SetInferenceRouteRequest)(nil),     // 2: openshell.inference.v1.SetInferenceRouteRequest
	(*ValidatedEndpoint)(nil),            // 3: openshell.inference.v1.ValidatedEndpoint
	(*SetInferenceRouteResponse)(nil),    // 4: openshell.inference.v1.SetInferenceRouteResponse
	(*GetInferenceRouteRequest)(nil),     // 5: openshell.inference.v1.GetInferenceRouteRequest
	(*GetInferenceRouteResponse)(nil),    // 6: openshell.inference.v1.GetInferenceRouteResponse
	(*DeleteInferenceRouteRequest)(nil),  // 7: openshell.inference.v1.DeleteInferenceRouteRequest
	(*DeleteInferenceRouteResponse)(nil), // 8: openshell.inference.v1.DeleteInferenceRouteResponse
	(*GetInferenceBundleRequest)(nil),    // 9: openshell.inference.v1.GetInferenceBundleRequest
	(*ResolvedRoute)(nil),                // 10: openshell.inference.v1.ResolvedRoute
	(*GetInferenceBundleResponse)(nil),   // 11: openshell.inference.v1.GetInferenceBundleResponse
	nil,                                  // 12: openshell.inference.v1.ResolvedRoute.DefaultHeadersEntry
	(*datamodelv1.ObjectMeta)(nil),       // 13: openshell.datamodel.v1.ObjectMeta
}
var file_inference_proto_depIdxs = []int32{
	13, // 0: openshell.inference.v1.InferenceRoute.metadata:type_name -> openshell.datamodel.v1.ObjectMeta
	0,  // 1: openshell.inference.v1.InferenceRoute.config:type_name -> openshell.inference.v1.InferenceRouteConfig
	3,  // 2: openshell.inference.v1.SetInferenceRouteResponse.validated_endpoints:type_name -> openshell.inference.v1.ValidatedEndpoint
	12, // 3: openshell.inference.v1.ResolvedRoute.default_headers:type_name -> openshell.inference.v1.ResolvedRoute.DefaultHeadersEntry
	10, // 4: openshell.inference.v1.GetInferenceBundleResponse.routes:type_name -> openshell.inference.v1.ResolvedRoute
	9,  // 5: openshell.inference.v1.Inference.GetInferenceBundle:input_type -> openshell.inference.v1.GetInferenceBundleRequest
	2,  // 6: openshell.inference.v1.Inference.SetInferenceRoute:input_type -> openshell.inference.v1.SetInferenceRouteRequest
	5,  // 7: openshell.inference.v1.Inference.GetInferenceRoute:input_type -> openshell.inference.v1.GetInferenceRouteRequest
	7,  // 8: openshell.inference.v1.Inference.DeleteInferenceRoute:input_type -> openshell.inference.v1.DeleteInferenceRouteRequest
	11, // 9: openshell.inference.v1.Inference.GetInferenceBundle:output_type -> openshell.inference.v1.GetInferenceBundleResponse
	4,  // 10: openshell.inference.v1.Inference.SetInferenceRoute:output_type -> openshell.inference.v1.SetInferenceRouteResponse
	6,  // 11: openshell.inference.v1.Inference.GetInferenceRoute:output_type -> openshell.inference.v1.GetInferenceRouteResponse
	8,  // 12: openshell.inference.v1.Inference.DeleteInferenceRoute:output_type -> openshell.inference.v1.DeleteInferenceRouteResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	file_inference_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
